#!/bin/sh
[ "$DEBUG" ] && set -x
set -e

# --
# @echo Warning if `.apt`
# Searches for `.apk` or `.apt` and installs or converts and installs.
# @return 0
# --
install_from_apk_file() {
  if [ "$1" = "apk" ] || [ -f ".apk" ]; then
    sudo touch /etc/apk/ran-user-install
    sudo apk --no-progress --update add "$(cat .apk)"
    $(root)/docker-helper cleanup

  elif [ -f ".apt" ]; then
    cp .apt /tmp/.apt

    sed -ri 's/^\s*libxslt1-dev/libxslt-dev/' /tmp/.apt
    sed -ri 's/^\s*build-essential/build-base/' /tmp/.apt
    sed -ri 's/^\s*libyaml-dev/yaml-dev/' /tmp/.apt
    sed -ri 's/^\s*libyaml/yaml/' /tmp/.apt

    mv /tmp/.apt .apk
    install_from_apk_file apk
    rm -rf .apk
  fi
}
