#!/bin/sh
[ "$DEBUG" ] && set -x
set -e

# --
# @echo Nothing
# Checks to see if a user install has been completed.
# @return 0
# --
user_pkgs_installed() {
  if [ -f /etc/apk/ran-user-install ] || [ -f /etc/apt/ran-user-install ]
    then return 0
    else return 1
  fi
}

# --
# @echo Nothing
# Installs packages from a `.apt` or `.apk` file depending on operating system.
# @return 0
# --
install_user_pkgs_from_file() {
  if [ "$(operating_system)" = "alpine" ]
    then install_from_apk_file
    else install_from_apt_file
  fi

  return 0
}

# --
# @echo Nothing
# Checks to see if the packager has been ran.
# @return 0
# --
user_pkg_installer_ran() {
  if [ "$(operating_system)" = "alpine" ]
    then test -f /etc/apk/ran-user-install
    else test -f /etc/apt/ran-user-install
  fi

  return 0
}
